# Generated by Django 4.2.4 on 2023-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dishName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dishes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('status', models.CharField(default='received', max_length=70)),
                ('order_dishes', models.ManyToManyField(to='restaurant.dish')),
            ],
        ),
    ]
